/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2020-06-15

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */

#include "stm32l4xx_hal.h"	//HAL library includes and micro definitions

#include "Sharc_Frame.h"	//Power config and timing for micro controller

#include "DATAFLASH.h"		//Flash Chip handling
/* Private macro */
/* Private variables */
RTC_HandleTypeDef hrtc;

/* Private function prototypes */

/**
  * @brief function t handle failiures in Peripheral initialization functions
  * @param None
  * @retval None
  */
void Error_Handler(void);



/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **  IMPORTANT NOTE!
 **  The symbol VECT_TAB_SRAM needs to be defined when building the project
 **  if code has been located to RAM and interrupts are used.
 **  Otherwise the interrupt table located in flash will be used.
 **  See also the <system_*.c> file and how the SystemInit() function updates
 **  SCB->VTOR register.
 **  E.g.  SCB->VTOR = 0x20000000;
 **
 **
 **===========================================================================
 **/

int main(void)
{
//======================== 1. SYSTEM INIT & CLOCK CONFIG ========================//

	HAL_Init();				//Init Flash prefetch, systick timer, NVIC and LL functions
	SystemClock_Config();	//configure clock
	GPIO_Set_Pin_LP();		//Configure all unused GPIO pins to low Power mode
	Init_Debug();			// initialize debug peripherals
	printf("Loading Data...\r\n");

	int i = 0;
	uint8_t statusbyte = 0;
	Init_Flash_Chips(&statusbyte);
	for (i = 0; i < 4; ++i)
	{
		uint8_t address[3] = {0,0,0};
		FLASH_SetAddress(address[2],address[1],address[0]);
		uint32_t add = 0;
		while(add < FLASH_MAX_ADDRESS)
		{
			//load a page from memory
			uint8_t buffer[256] = {0};
			memcpy(buffer,FLASH_READ_BufferHF(i,BUFFER1),256);
			FLASH_IncAddress(256);
			//increment address
			add = FLASH_GetAddress();
		}
	}
		while(1)
		{

		}
}

/**
**=======================================================================================
**
**  								END OF MAIN PROGRAM
**
**=======================================================================================
*/


//==================================== 8. Handlers ===================================//

void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */

  /* USER CODE END Error_Handler_Debug */
}

//===================================== 8. END ======================================//
